name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Trigger docs-site build
      run: |
        curl -X POST ${{ secrets.WEBHOOK_URL }} \
        -H 'Authorization: token ${{ secrets.WEBHOOK_TOKEN }}' \
        --fail \
        --data '{"event_type": "deploy_docs_site"}'
